{{ if eq .Values.env "stage" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: optimize-configmap
  labels: {{ include "commonLabels" $ | nindent 4 }}
  annotations: {{ include "commonAnnotations" $ | nindent 4 }}
data:
  ######################## OPT ########################
  OptimizeLicense.txt: |
    --------------- BEGIN OPTIMIZE FAKE KEY ---------------
    redactedredactedredactedredactedredactedredactedredactedre
    redactedredactedredactedredactedredactedredactedredactedre
    redactedredactedredactedredactedredactedredactedredactedre
    redactedredactedredactedredactedredactedredactedredactedre
    redactedredactedredactedredactedredactedredactedredactedre
    redactedredactedredactedredactedredactedredactedredacte
    schrottis inn;unlimited
    ---------------  END OPTIMIZE LICENSE KEY  ---------------

  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    node.processors: 2

  environment-config.yaml: |
    ###############################################################################
    #                                                                             #
    #                     Optimize Environment Configuration                      #
    #                                                                             #
    ###############################################################################

    # Note: for all possible configuration options please have a look
    #       at the Optimize documentation:
    #       https://docs.camunda.io/optimize/self-managed/optimize-deployment/configuration/getting-started/
    security:
      # everything that's related to authentication
      auth:
        cookie:
          same-site:
            # decides if the optimize auth cookie has the same site cookie flag set
            enabled: true
        token:
          # Optimize uses token-based authentication to keep track of which users are
          # logged in. Define when a token is supposed to expire.
          lifeMin: 60
          # Optional secret used to sign authentication tokens, it's recommended to use at least a 64 character secret.
          # If set `null` a random secret will be generated with each startup of Optimize.
          secret: null
        # List of user ids that are granted full permission to all collections, reports & dashboards
        # Note: For reports these users are still required to be granted access to the corresponding process/decision
        # definitions in Camunda BPM Admin
        superUserIds: ['demo']
    
    api:
      accessToken: secret

    import:
      customer-onboarding: true
      skipDataAfterNestedDocLimitReached: true

    container:
      # A host name or IP address, to identify a specific network interface on
      # which to listen.
      host: 0.0.0.0
      ports:
        # A port number that will be used by the embedded jetty server to process
        # HTTP connections.
        http: 8090
        # A port number that will be used by the embedded jetty server to process
        # secure HTTPS connections.
        https: 8091
      accessUrl: 'https://stage.optimize.camunda.cloud'

    # Configuration for engines used to import data. Please note that you have to have at
    # least one engine configured at all times.
    engines:
      # An alias of the engine, which will be used for internal purposes like
      # logging and displaying which data belong to which engine.
      'camunda-bpm':
        # The name of the engine that will be used to import data.
        name: default
        # A base URL that will be used for connections to the Camunda Engine REST API.
        rest: 'http://localhost:8080/engine-rest'
        importEnabled: true
        eventImportEnabled: true
        authentication:
          #Toggles basic authentication on or off. When enabling basic
          #authentication, please be aware that you also need to adjust the values
          #of the user and password
          enabled: false
          #When basic authentication is enabled, this password is used to
          #authenticate against the engine.
          password: ''
          #When basic authentication is enabled, this user is used to authenticate
          #against the engine.
          user: ''
        # The webapps configuration allows Optimize to directly link
        # to the other Camunda Web Applications, e.g. to jump from
        # Optimize directly to a dedicated process instance in Cockpit
        webapps:
          # Defines the endpoint where to find the camunda webapps
          endpoint: 'https://stage.optimize.camunda.cloud/camunda'
          # Enables/disables linking to other Camunda Web Applications
          enabled: true
    es:
      connection:
        #Maximum time without connection to Elasticsearch, Optimize should
        #wait until a time out triggers.
        timeout: 10000
        # a list of Elasticsearch nodes Optimize can connect to. If you  have built
        # an Elasticsearch cluster with several nodes it is recommended to define
        # several connection points in case one node fails.
        nodes:
            # the address/hostname under which the Elasticsearch node is available.
          - host: 'localhost'
            # A port number used by Elasticsearch to accept HTTP connections.
            httpPort: 9200
      settings:
        index:
          number_of_replicas: 0

    serialization:
      # Define a custom date format that should be used for
      # fetching date data from the engine(should be the same as in the engine)
      engineDateFormat: yyyy-MM-dd'T'HH:mm:ss.SSSZ

    eventBasedProcess:
      authorizedUserIds: ['demo']
      eventImport:
        enabled: true

    webhookAlerting:
      webhooks:
        # This Webhook sends a message to the slack channel `optimize-stage-alerts`
        'SlackWebhook':
          # URL of the webhook which can receive alerts from Optimize
          url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
          # Map of the headers of the request sent to the webhook URL
          headers:
            'Content-type': 'application/json'
          # HTTP Method for the webhook request
          httpMethod: 'POST'
          # The default payload structure with the alertMessagePlaceholder {{ "{{" }}ALERT_MESSAGE{{ "}}" }} for the alert text.
          # Optimize will replace this placeholder with the content of the alert message.
          defaultPayload: '{"text": "{{ "{{" }}ALERT_MESSAGE{{ "}}" }}"}'
        'SlackWebhookCustomContent':
          url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
          headers:
            'Content-type': 'application/json'
          httpMethod: 'POST'
          defaultPayload: '{"text": "The alert *{{ "{{" }}ALERT_NAME{{ "}}" }}* was triggered as *{{ "{{" }}ALERT_TYPE{{ "}}" }}*, you can view the report <{{ "{{" }}ALERT_REPORT_LINK{{ "}}" }}|here>."}'
    telemetry:
      # Sets the initial property value of telemetry configuration once when it has never been enabled/disabled before.
      # Telemetry can later be enabled/disabled in the UI by superusers
      initializeTelemetry: false
      # Interval for telemetry reporting, defaults to every 24 hours.
      reportingIntervalInHours: 24

    analytics:
      enabled: true
      osano:
        scriptUrl: 'https://cmp.osano.com/16CVvwSNKHi9t1grQ/2eb9efaf-2122-4d98-941a-a3ed291e1c48/osano.js'
      mixpanel:
        token: '9fa7e6a44e46c212210e439b1bbed222'
        properties:
          stage: 'optimize-staging'
          organizationId: 'optimize-staging'
          clusterId: 'optimize-staging'

  ######################## CAM BPM ########################
  configure-and-run.sh: |
    #!/bin/bash -ex
    # remove unneeded webapps
    for webapp in camunda-invoice camunda-welcome docs examples host-manager manager h2 ROOT
    do
       rm -rf ${HOME}/webapps/${webapp}
    done

    exec ${HOME}/camunda.sh

  bpm-platform.xml: |
    <?xml version='1.0' encoding='UTF-8'?>
    <bpm-platform xmlns="http://www.camunda.org/schema/1.0/BpmPlatform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.camunda.org/schema/1.0/BpmPlatform http://www.camunda.org/schema/1.0/BpmPlatform ">
        <job-executor>
            <job-acquisition name="default" />
            <properties>
                <!-- configure threadpool size to minimum -->
                <!-- Note: the following properties only take effect in a Tomcat environment -->
                <property name="queueSize">1</property>
                <property name="corePoolSize">1</property>
                <property name="maxPoolSize">1</property>
                <property name="keepAliveTime">0</property>
              </properties>
        </job-executor>
        <process-engine name="default">
            <job-acquisition>default</job-acquisition>
            <configuration>org.camunda.bpm.engine.impl.cfg.StandaloneProcessEngineConfiguration</configuration>
            <datasource>java:jdbc/ProcessEngine</datasource>
            <properties>
                <property name="history">full</property>
                <property name="databaseSchemaUpdate">false</property>
                <property name="authorizationEnabled">false</property>
                <property name="jobExecutorDeploymentAware">false</property>
                <!-- disable job executor -->
                <property name="jobExecutorActivate">false</property>
            </properties>

            <plugins>
                <!-- plugin enabling Process Application event listener support -->
                <plugin>
                  <class>org.camunda.bpm.application.impl.event.ProcessApplicationEventListenerPlugin</class>
                </plugin>
                <!-- plugin enabling integration of camunda Spin -->
                <plugin>
                  <class>org.camunda.spin.plugin.impl.SpinProcessEnginePlugin</class>
                </plugin>
                <!-- plugin enabling connect support -->
                <plugin>
                  <class>org.camunda.connect.plugin.impl.ConnectProcessEnginePlugin</class>
                </plugin>
            </plugins>
        </process-engine>
    </bpm-platform>

  server.xml: |
    <?xml version='1.0' encoding='UTF-8'?>
    <Server port="8005" shutdown="SHUTDOWN">
      <Listener className="org.apache.catalina.startup.VersionLoggerListener" />
      <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
      <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
      <Listener className="org.camunda.bpm.container.impl.tomcat.TomcatBpmPlatformBootstrap" />
      <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
      <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />
      <GlobalNamingResources>
        <Resource name="UserDatabase" auth="Container"
                  type="org.apache.catalina.UserDatabase"
                  description="User database that can be updated and saved"
                  factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
                  pathname="conf/tomcat-users.xml" />
        <Resource name="jdbc/ProcessEngine"
                  auth="Container"
                  type="javax.sql.DataSource"
                  factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
                  uniqueResourceName="process-engine"
                  driverClassName="org.postgresql.Driver"
                  url="jdbc:postgresql://stage-postgres.optimize:5432/optimize-ci-performance"
                  defaultTransactionIsolation="READ_COMMITTED"
                  username="camunda"
                  password="camunda123"
                  initialSize="10"
                  maxTotal="20"
                  minIdle="5"
                  maxIdle="10"
                  validationQuery="SELECT 1"
                  validationQueryTimeout="30"
                  testOnBorrow="true"
                  testWhileIdle="true"
                  removeAbandonedOnBorrow="true"
                  removeAbandonedTimeout="300"
                  logAbandoned="true"
                  logExpiredConnections="true"
                  defaultQueryTimeout="60" />
        <Resource name="global/camunda-bpm-platform/process-engine/ProcessEngineService!org.camunda.bpm.ProcessEngineService" auth="Container"
                  type="org.camunda.bpm.ProcessEngineService"
                  description="camunda BPM platform Process Engine Service"
                  factory="org.camunda.bpm.container.impl.jndi.ProcessEngineServiceObjectFactory" />
        <Resource name="global/camunda-bpm-platform/process-engine/ProcessApplicationService!org.camunda.bpm.ProcessApplicationService" auth="Container"
                  type="org.camunda.bpm.ProcessApplicationService"
                  description="camunda BPM platform Process Application Service"
                  factory="org.camunda.bpm.container.impl.jndi.ProcessApplicationServiceObjectFactory" />
      </GlobalNamingResources>
      <Service name="Catalina">
        <Connector port="8080" protocol="HTTP/1.1"
                   connectionTimeout="20000"
                   redirectPort="8443" />
        <Engine name="Catalina" defaultHost="localhost">
          <Realm className="org.apache.catalina.realm.LockOutRealm">
            <Realm className="org.apache.catalina.realm.UserDatabaseRealm"
                   resourceName="UserDatabase"/>
          </Realm>
          <Host name="localhost"  appBase="webapps"
                unpackWARs="true" autoDeploy="true">
            <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
                   prefix="localhost_access_log" suffix=".txt"
                   pattern="%h %l %u %t &quot;%r&quot; %s %b" />
          </Host>
        </Engine>
      </Service>
    </Server>

{{ end }}