---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: optimize
  labels: {{ include "commonLabels" $ | nindent 4 }}
  annotations: {{ include "commonAnnotations" $ | nindent 4 }}{{ include "infrapreviewenvironmentsingress.annotations" $ | nindent 4 }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ include "ingress.domain" $ | quote }}
    secretName: optimize-tls
  rules:
  - host: {{ include "ingress.domain" $ | quote }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: optimize
            port:
              number: 8090
      - path: /camunda
        pathType: ImplementationSpecific
        backend:
          service:
            name: optimize
            port:
              number: 8080
      - path: /engine-rest
        pathType: ImplementationSpecific
        backend:
          service:
            name: optimize
            port:
              number: 8080
      - path: /mail
        pathType: ImplementationSpecific
        backend:
          service:
            name: optimize
            port:
              number: 8025
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: optimize-external
  labels: {{ include "commonLabels" $ | nindent 4 }}
  annotations: {{ include "commonAnnotations" $ | nindent 4 }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ include "ingress.domain" $ | quote }}
      secretName: optimize-tls
  rules:
    - host: {{ include "ingress.domain" $ | quote }}
      http:
        paths:
          - path: /external
            pathType: ImplementationSpecific
            backend:
              service:
                name: optimize
                port:
                  number: 8090
