---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-camunda-cloud
  labels: {{ include "commonLabels" $ | nindent 4 }}
  annotations: {{ include "commonAnnotations" $ | nindent 4 }}
spec:
  refreshInterval: "5m"

  secretStoreRef:
    name: optimize-vault-backend
    kind: ClusterSecretStore

  target:
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          managed-by: external-secrets

  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: secret/data/k8s-camunda-ci/optimize/ci-optimize-camunda-cloud
        property: REGISTRY_CAMUNDA_CLOUD_DOCKERCONFIGJSON
