---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-camunda-cloud
  namespace: ${NAMESPACE}
spec:
  refreshInterval: "5m"

  secretStoreRef:
    name: optimize-vault-backend
    kind: ClusterSecretStore

  target:
    template:
      type: kubernetes.io/dockerconfigjson

  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: secret/data/k8s-camunda-ci/optimize/ci-optimize-camunda-cloud
        property: REGISTRY_CAMUNDA_CLOUD_DOCKERCONFIGJSON
