es.clusterName: '/technical-guide/setup/configuration/#connection-settings'
es.host: '/technical-guide/setup/configuration/#connection-settings'
es.ports.tcp: '/technical-guide/setup/configuration/#connection-settings'
es.ports.http: '/technical-guide/setup/configuration/#connection-settings'
es.sampler.interval: '/technical-guide/setup/configuration/#connection-settings'
es.connection.nodes[*].tcpPort: '/technical-guide/setup/configuration/#connection-settings'
es.connection.clusterName: '/technical-guide/setup/configuration/#connection-settings'
es.connection.samplerInterval: '/technical-guide/setup/configuration/#connection-settings'
es.security.ssl.key: '/technical-guide/setup/configuration/#security-settings'
es.security.ssl.verification_mode: '/technical-guide/setup/configuration/#security-settings'
alerting.email: '/technical-guide/setup/configuration/#email'
email.username: '/technical-guide/setup/configuration/#email'
email.password: '/technical-guide/setup/configuration/#email'
auth.cookie.same-site: '/technical-guide/setup/configuration/#security'
auth.cookie.token.lifeMin: '/technical-guide/setup/configuration/#security'
auth.cookie.token.secret: '/technical-guide/setup/configuration/#security'
auth.superUserIds: '/technical-guide/setup/configuration/#security'
historyCleanup.enabled: '/technical-guide/setup/configuration/#history-cleanup-settings'
historyCleanup.processDataCleanupMode: '/technical-guide/setup/configuration/#history-cleanup-settings'
historyCleanup.perProcessDefinitionConfig: '/technical-guide/setup/configuration/#history-cleanup-settings'
historyCleanup.perDecisionDefinitionConfig: '/technical-guide/setup/configuration/#history-cleanup-settings'
eventBasedProcess.eventIngestion.accessToken: '/technical-guide/setup/configuration/#public-api'
externalVariable.variableIngestion.accessToken: '/technical-guide/setup/configuration/#public-api'
ui.header.textColor: '/optimize/self-managed/optimize-deployment/configuration/system-configuration/#ui-configuration'
ui.header.pathToLogoIcon: '/optimize/self-managed/optimize-deployment/configuration/system-configuration/#ui-configuration'
ui.header.backgroundColor: '/optimize/self-managed/optimize-deployment/configuration/system-configuration/#ui-configuration'
telemetry.telemetryEndpoint: '/technical-guide/setup/configuration/'