---
container:
  ports:
    http: ${optimizeHttpPort:8090}
    https: ${optimizeHttpsPort:8091}
  enableSniCheck: false

api:
  accessToken: secret

engines:
  'camunda-bpm':
    name: ${prefixedDefaultEngineName:integrationTest}
    rest: 'http://localhost:8080/engine-rest'
    importEnabled: true
    authentication:
      enabled: false
      password: ''
      user: ''
    webapps:
      endpoint: 'http://localhost:8080/camunda/'
      enabled: true

import:
  data:
    process-definition-xml:
      pageSize:
        max: 30
  elasticsearchJobExecutorThreadCount: 1
  currentTimeBackoffMilliseconds: 0
es:
  scrollTimeoutInSeconds: 5
  settings:
    index:
      prefix: ${indexPrefix:optimize}
      # we need to limit the shards to one so that ElasticSearch does not create too
      # many scroll contexts. Context: before/after each integration test we're
      # doing a `delete by query` request, which does scrolling on its own for
      # each shard that exists.
      number_of_shards: 1
opensearch:
  scrollTimeoutInSeconds: 5
  settings:
    index:
      prefix: ${indexPrefix:optimize}
      # we need to limit the shards to one so that OpenSearch does not create too
      # many scroll contexts. Context: before/after each integration test we're
      # doing a `delete by query` request, which does scrolling on its own for
      # each shard that exists.
      number_of_shards: 1

eventBasedProcess:
  authorizedUserIds: ['demo']

plugin:
  # as default just use an existing directory
  directory: '.'
