services:
  cambpm:
    image: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee:${CAMBPM_VERSION:-7.19.0}
    container_name: cambpm
    environment:
      - TZ=Europe/Berlin
      - JAVA_OPTS=-Xms512m -Xmx512m -XX:MaxMetaspaceSize=256m
    ports:
      - 8080:8080
    restart: always
    cpu_count: 1
    mem_limit: 1g
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:8080/engine-rest/engine | grep -q default"]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx-ssl-basic-auth:
    image: 'beevelop/nginx-basic-auth'
    container_name: nginx-ssl-basic-auth
    ports:
      - '9200:81'
    volumes:
      - "./src/test/resources/nginx/ssl-basic-auth.cfg:/opt/auth.conf:ro"
      - "./src/test/resources/certs/optimize/optimize.crt:/etc/nginx/certs/optimize.crt:ro"
      - "./src/test/resources/certs/optimize/optimize.key:/etc/nginx/certs/optimize.key:ro"
    environment:
      - PORT=81
      - FORWARD_HOST=elasticsearch
      - FORWARD_PORT=9203
      - HTPASSWD=elastic:$$apr1$$rAPWdsDW$$/7taaK2oH4AwXgLTbYSpa0

  nginx-ssl:
    image: 'beevelop/nginx-basic-auth'          # using "basic auth" image but basic auth not enabled in ssl-auth.cfg
    container_name: nginx-ssl
    ports:
      - '9201:82'
    volumes:
      - "./src/test/resources/nginx/ssl-auth.cfg:/opt/auth.conf:ro"
      - "./src/test/resources/certs/optimize/optimize.crt:/etc/nginx/certs/optimize.crt:ro"
      - "./src/test/resources/certs/optimize/optimize.key:/etc/nginx/certs/optimize.key:ro"
    environment:
      - PORT=82
      - FORWARD_HOST=elasticsearch
      - FORWARD_PORT=9203

  nginx-nossl-basic-auth:
    image: 'beevelop/nginx-basic-auth'
    container_name: nginx-nossl-basic-auth
    ports:
      - '80:80'
    environment:
      - FORWARD_HOST=elasticsearch
      - FORWARD_PORT=9203
      - HTPASSWD=elastic:$$apr1$$rAPWdsDW$$/7taaK2oH4AwXgLTbYSpa0

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION:-8.9.0}
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - http.port=9203
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - action.destructive_requires_name=false
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9203:9203
    restart: always
    cpu_count: 2
    mem_limit: 1g
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:9203/_cat/health | grep -q -E 'yellow|green'"]
      interval: 10s
      timeout: 5s
      retries: 6

  wait_until_ready:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION:-7.10.0}
    command: /usr/bin/true
    depends_on: {
      "elasticsearch": {"condition": "service_healthy"}
    }