name: Login to Google Cloud
description: |
  Local action to simplify login to Google Cloud
inputs:
  secrets:
    description: JSON wrapped secrets for easier secret passing
    required: true
  project_id:
    description: Google Cloud project ID
    required: false
    default: ci-30-162810
runs:
  using: composite
  steps:
    - name: Import secrets
      id: secrets
      uses: hashicorp/vault-action@148ee648ccb26f28892776406f3c3c4cf8ac033f
      with:
        url: ${{ fromJSON(inputs.secrets).VAULT_ADDR }}
        method: approle
        roleId: ${{ fromJSON(inputs.secrets).VAULT_ROLE_ID }}
        secretId: ${{ fromJSON(inputs.secrets).VAULT_SECRET_ID }}
        secrets: |
          secret/data/products/optimize/ci/camunda-optimize CI_SERVICE_ACCOUNT | GCP_CREDENTIALS;
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa # v2
      with:
        credentials_json: ${{ steps.secrets.outputs.GCP_CREDENTIALS }}

    - name: Configure Google SDK
      uses: google-github-actions/setup-gcloud@98ddc00a17442e89a24bbf282954a3b65ce6d200 # v2.1.0
      with:
        project_id: ${{ inputs.project_id }}
        install_components: gke-gcloud-auth-plugin, kubectl
