services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION:-8.9.0}
    container_name: elasticsearch
    environment:
      - TZ=Europe/Berlin
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - cluster.name=elasticsearch
      - cluster.routing.allocation.disk.watermark.high=95%
      - cluster.routing.allocation.disk.watermark.high.max_headroom=150GB
      - action.destructive_requires_name=false
      - http.port=9200
      - ES_JAVA_OPTS=-Xms${ELASTIC_JVM_MEMORY:-1}g -Xmx${ELASTIC_JVM_MEMORY:-1}g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    cpu_count: 4
    mem_limit: 2g
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9200/_cat/health | grep -q green']
      interval: 30s
      timeout: 5s
      retries: 3
  zeebe:
    image: camunda/zeebe:${ZEEBE_VERSION:-8.5.0}
    profiles: ['cloud', 'self-managed']
    container_name: zeebe
    environment:
      - 'JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m'
    ports:
      - '26500:26500'
      - '9600:9600'
    healthcheck:
      test: ['CMD-SHELL', "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9600' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always
    volumes:
      - ../zeebe-application.yml:/usr/local/zeebe/config/application.yaml
    depends_on:
      - elasticsearch
  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:24.0.4@sha256:cc599cbd15ff5701e1fe6709d7e45dc143066ca555b1214dcab40bfd4c459357
    profiles: ['self-managed']
    ports:
      - '18080:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/auth']
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_VENDOR: dev-file
      KEYCLOAK_HTTP_RELATIVE_PATH: /auth
  identity:
    depends_on:
      - keycloak
    restart: on-failure
    container_name: identity
    image: camunda/identity:latest
    profiles: ['self-managed']
    ports:
      - '8081:8081'
    healthcheck:
      test: ['CMD', 'wget', '-q', '--tries=1', '--spider', 'http://localhost:8082/actuator/health']
      interval: 5s
      timeout: 15s
      retries: 30
      start_period: 60s
    environment:
      SERVER_PORT: 8081
      KEYCLOAK_URL: http://keycloak:8080/auth
      IDENTITY_AUTH_PROVIDER_BACKEND_URL: http://keycloak:8080/auth/realms/camunda-platform
      KEYCLOAK_INIT_OPTIMIZE_SECRET: XALaRPl5qwTEItdwCMiPS62nVpKs7dL7
      KEYCLOAK_INIT_OPTIMIZE_ROOT_URL: http://localhost:3000
      KEYCLOAK_USERS_0_USERNAME: 'ourief'
      KEYCLOAK_USERS_0_PASSWORD: 'ourief'
      KEYCLOAK_USERS_0_FIRST_NAME: 'ourief'
      KEYCLOAK_USERS_0_ROLES_0: 'Identity'
      KEYCLOAK_USERS_0_ROLES_1: 'Optimize'
      KEYCLOAK_USERS_1_USERNAME: 'comentse'
      KEYCLOAK_USERS_1_PASSWORD: 'comentse'
      KEYCLOAK_USERS_1_FIRST_NAME: 'comentse'
      KEYCLOAK_USERS_1_ROLES_0: 'Optimize'
      KEYCLOAK_USERS_2_USERNAME: 'abook1998'
      KEYCLOAK_USERS_2_PASSWORD: 'abook1998'
      KEYCLOAK_USERS_2_FIRST_NAME: 'abook1998'
      KEYCLOAK_USERS_2_ROLES_0: 'Optimize'
      KEYCLOAK_USERS_3_USERNAME: 'aboys1960'
      KEYCLOAK_USERS_3_PASSWORD: 'aboys1960'
      KEYCLOAK_USERS_3_FIRST_NAME: 'aboys1960'
      KEYCLOAK_USERS_3_ROLES_0: 'Optimize'
      KEYCLOAK_USERS_4_USERNAME: 'abrount'
      KEYCLOAK_USERS_4_PASSWORD: 'abrount'
      KEYCLOAK_USERS_4_FIRST_NAME: 'abrount'
      KEYCLOAK_USERS_4_ROLES_0: 'Optimize'
      KEYCLOAK_USERS_5_USERNAME: 'abse1978'
      KEYCLOAK_USERS_5_PASSWORD: 'abse1978'
      KEYCLOAK_USERS_5_FIRST_NAME: 'abse1978'
      KEYCLOAK_USERS_5_ROLES_0: 'Optimize'
      KEYCLOAK_USERS_6_USERNAME: 'demo'
      KEYCLOAK_USERS_6_PASSWORD: 'demo'
      KEYCLOAK_USERS_6_EMAIL: 'demo@demo.com'
      KEYCLOAK_USERS_6_FIRST_NAME: 'demo'
      KEYCLOAK_USERS_6_ROLES_0: 'Optimize'
      KEYCLOAK_USERS_6_ROLES_1: 'Identity'
  operate:
    profiles: ['self-managed']
    image: camunda/operate:${OPERATE_VERSION:-8.5.0}
    container_name: operate
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ARCHIVER_WAITPERIODBEFOREARCHIVING=1m
      - SPRING_PROFILES_ACTIVE=dev-data
      - CAMUNDA_OPERATE_IDENTITY_ISSUER_URL=http://localhost:18080/auth/realms/camunda-platform
      - CAMUNDA_OPERATE_IDENTITY_ISSUER_BACKEND_URL=http://localhost:18080/auth/realms/camunda-platform
      - CAMUNDA_OPERATE_IDENTITY_CLIENT_ID=operate
      - CAMUNDA_OPERATE_IDENTITY_CLIENT_SECRET=the-cake-is-alive
      - CAMUNDA_OPERATE_IDENTITY_AUDIENCE=operate-api
      - CAMUNDA_OPERATE_BACKUP_REPOSITORYNAME=test
      - SERVER_SERVLET_CONTEXT_PATH=/
      - CAMUNDA_OPERATE_CLUSTERNODE_PARTITIONIDS=1,2
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD-SHELL', "wget -O - -q 'http://localhost:8080/actuator/health/readiness'"]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    depends_on:
      - elasticsearch
      - zeebe
    restart: always
