---
# Default values for c7-optimize.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

git:
  # Defines the branch name to use for annotating resources
  branch: master
  # Defines the repository URL to use for annotating resources
  repoUrl: https://github.com/camunda/camunda-optimize

replicaCount: 1

# this Chart serves stage environment
env: stage

ingress:
  # Defines the domain under which to expose the ingress
  domain: optimize.camunda.cloud

# Tags is usually overridden to a specific tag produced by CI
optimize:
  image:
    repository: registry.camunda.cloud/team-optimize/optimize
    tag: latest
  resources:
    limits:
      cpu: 4
      memory: 3Gi
    requests:
      cpu: 4
      memory: 3Gi

cambpm:
  image:
    repository: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee
    tag: latest
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 2
      memory: 2Gi

mailhog:
  image:
    repository: mailhog/mailhog
    tag: v1.0.1

elasticsearch:
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 8.13.3@sha256:55cf51620ffd4a27b661ad9d091dc06446f7aeaf4045744d4e7ef6480d390596
  resources:
    limits:
      cpu: 4
      memory: 10Gi
    requests:
      cpu: 4
      memory: 10Gi

nameOverride: ""
fullnameOverride: ""


# Configuration of global values as required by the camunda-platform chart and to comply
# with Infra best practices.
global:
  labels:
    camunda.cloud/source: argocd
    camunda.cloud/managed-by: Helm
    app: optimize-camunda-cloud # Should be overridden by Argo app
    team: optimize
