webhookAlerting:
  webhooks:
    # Name of the webhook, must be unique.
    'testWebhook':
      # URL of the webhook which can receive alerts from Optimize
      url: 'someUrl'
      # Map of the headers of the request to the sent to the webhook URL
      headers:
        'Authorization': 'auth token'
        'Content-type': 'application/json'
      # HTTP Method for the webhook request
      httpMethod: 'POST'
      # The default payload structure with the alertMessagePlaceholder {{ALERT_MESSAGE}} for the alert text.
      # Optimize will replace this placeholder with the content of the alert message.
      defaultPayload: '{"text": "{{ALERT_MESSAGE}}"}'
zeebe:
  # Toggles whether Optimize should attempt to import data from the connected Zeebe instance
  enabled: ${ZEEBE_IMPORT_ENABLED:false}
  partitionCount: 2
