name: Setup Maven
description: |
  Maven wrapper to abstract defaults for setting maven up
inputs:
  java-version:
    description: Java version to be used
    required: false
    default: '21'
  distribution:
    description: Java distribution to be used
    required: false
    default: 'temurin'
  maven-version:
    description: Maven version to be used
    required: false
    default: '3.8.6'
  secrets:
    description: JSON wrapped secrets for easier secret passing
    required: true
runs:
  using: composite
  steps:
  - name: Import secrets
    id: secrets
    uses: hashicorp/vault-action@148ee648ccb26f28892776406f3c3c4cf8ac033f
    with:
      url: ${{ fromJSON(inputs.secrets).VAULT_ADDR }}
      method: approle
      roleId: ${{ fromJSON(inputs.secrets).VAULT_ROLE_ID }}
      secretId: ${{ fromJSON(inputs.secrets).VAULT_SECRET_ID }}
      secrets: |
        secret/data/products/optimize/ci/optimize NEXUS_USERNAME;
        secret/data/products/optimize/ci/optimize NEXUS_PASSWORD;
  - name: Setup Maven Action
    uses: s4u/setup-maven-action@489441643219d2b93ee2a127b2402eb640a1b947 # v1.13.0
    with:
      java-version: ${{ inputs.java-version }}
      java-distribution: ${{ inputs.distribution }}
      maven-version: ${{ inputs.maven-version }}
  - name: 'Create settings.xml'
    uses: s4u/maven-settings-action@7802f6aec16c9098b4798ad1f1d8ac75198194bd # v3.0.0
    with:
      githubServer: false
      servers: |
        [{
          "id": "camunda-nexus",
          "username": "${{ steps.secrets.outputs.NEXUS_USERNAME }}",
          "password": "${{ steps.secrets.outputs.NEXUS_PASSWORD }}"
        }]
      mirrors: '[{"url": "https://repository.nexus.camunda.cloud/content/groups/internal/", "id": "camunda-nexus", "mirrorOf": "*", "name": "camunda Nexus"}]'
  # workaround, maven has troubles creating a subdirectory of a non existing directory
  - shell: bash
    run: mkdir -p ${{ github.workspace }}/optimize/backend/target/classes/
  - shell: bash
    run: |
      sudo rm -rf /etc/localtime
      sudo ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
