apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-optimize-camunda-cambpm-cloud
  namespace: ${NAMESPACE}
  labels:
    team: optimize
spec:
  progressDeadlineSeconds: 1800
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: cambpm
  template:
    metadata:
      labels:
        app: cambpm
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: agents-n1-standard-8-netssd-stable
      tolerations:
        - key: "agents-n1-standard-8-netssd-stable"
          operator: "Exists"
          effect: "NoSchedule"
      imagePullSecrets:
        - name: registry-camunda-cloud
      containers:
        - name: cambpm
          image: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee:${CAMBPM_VERSION}
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: "-Xmx512m -XX:MaxMetaspaceSize=128m"
          ports:
            - containerPort: 8080
              name: cambpm-http
          tty: true
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            httpGet:
              path: /engine-rest/engine
              port: cambpm-http
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            httpGet:
              path: /engine-rest/engine
              port: cambpm-http
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 2
              memory: 1Gi
