---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-optimize-import-camunda-cloud
  namespace: ${NAMESPACE}
  labels:
    app: optimize
data:
  ######################## OPT ########################
  OptimizeLicense.txt: |
    --------------- BEGIN OPTIMIZE FAKE KEY ---------------
    redactedredactedredactedredactedredactedredactedredactedre
    redactedredactedredactedredactedredactedredactedredactedre
    redactedredactedredactedredactedredactedredactedredactedre
    redactedredactedredactedredactedredactedredactedredactedre
    redactedredactedredactedredactedredactedredactedredactedre
    redactedredactedredactedredactedredactedredactedredacte
    schrottis inn;unlimited
    ---------------  END OPTIMIZE LICENSE KEY  ---------------

  environment-config.yaml: |
    security:
      auth:
        token:
          secret: 'redactedredactedredactedredactedredactedredactedredactedredacted'

    container:
      host: 0.0.0.0
      ports:
        http: 8090
        https: 8091

    engines:
      'camunda-bpm':
        name: default
        rest: 'http://cambpm:8080/engine-rest'
        authentication:
          enabled: false
        webapps:
          endpoint: 'http://cambpm:8080/camunda'
          enabled: true
        # this instance is importing
        importEnabled: true

    es:
      connection:
        nodes:
        - host: 'elasticsearch'
          httpPort: 9200

---
kind: Service
apiVersion: v1
metadata:
  name: optimize-import
  namespace: ${NAMESPACE}
spec:
  selector:
    app: optimize-import
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      name: optimize-http
