---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cluster-optimize-no-import-camunda-cloud
  namespace: ${NAMESPACE}
  labels:
    team: optimize
spec:
  selector:
    matchLabels:
      app: optimize-no-import
  serviceName: optimize-no-import
  podManagementPolicy: Parallel
  replicas: 3
  template:
    metadata:
      labels:
        app: optimize-no-import
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: agents-n1-standard-8-netssd-preempt
      imagePullSecrets:
        - name: registry-camunda-cloud
      tolerations:
        - key: "agents-n1-standard-8-netssd-preempt"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
        - name: configuration
          configMap:
            name: cluster-optimize-no-import-camunda-cloud
            defaultMode: 0744
      containers:
        - name: optimize-no-import
          image: registry.camunda.cloud/team-optimize/optimize:latest
          imagePullPolicy: Always
          env:
            - name: OPTIMIZE_JAVA_OPTS
              value: |
                -Xms512m
                -Xmx512m
                -XX:MaxMetaspaceSize=128m
          ports:
            - containerPort: 8090
              name: optimize-http
              protocol: TCP
          tty: true
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
            httpGet:
              path: /
              port: optimize-http
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
            httpGet:
              path: /api/readyz
              port: optimize-http
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 2
              memory: 1Gi
          volumeMounts:
            - name: configuration
              mountPath: /optimize/config/environment-config.yaml
              subPath: environment-config.yaml
            - name: configuration
              mountPath: /optimize/config/OptimizeLicense.txt
              subPath: OptimizeLicense.txt
