services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION:-8.9.0}
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - action.destructive_requires_name=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    restart: always
    cpu_count: 2
    mem_limit: 2g
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cat/health | grep -q green"]
      interval: 30s
      timeout: 5s
      retries: 3
  cambpm:
    image: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee:${CAMBPM_VERSION:-7.19.0}
    container_name: cambpm
    environment:
      - TZ=Europe/Berlin
      - JAVA_OPTS=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m
    ports:
      - 8080:8080
      - 9092:9092
    restart: always
    cpu_count: 1
    mem_limit: 2g
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:8080/engine-rest/engine | grep -q default"]
      interval: 30s
      timeout: 5s
      retries: 3
  optimize-import:
    build: ./target/docker/optimize
    container_name: optimize-import
    environment:
      - TZ=Europe/Berlin
      - OPTIMIZE_JAVA_OPTS=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m
    ports:
      - 8090:8090
    volumes:
      - "./src/test/resources/OptimizeLicense.txt:/optimize/config/OptimizeLicense.txt"
      - "./src/test/resources/optimize-import-cfg.yml:/optimize/config/environment-config.yaml"
    restart: always
    cpu_count: 1
    mem_limit: 2g
  optimize-no-import:
    build: ./target/docker/optimize
    container_name: optimize-no-import
    environment:
      - TZ=Europe/Berlin
      - OPTIMIZE_JAVA_OPTS=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m
    ports:
      - 8190:8090
    volumes:
      - "./src/test/resources/OptimizeLicense.txt:/optimize/config/OptimizeLicense.txt"
      - "./src/test/resources/optimize-no-import-cfg.yml:/optimize/config/environment-config.yaml"
    restart: always
    cpu_count: 1
    mem_limit: 2g
