services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION:-7.10.0}
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    cpu_count: 2
    mem_limit: 2g
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cat/health | grep -q green"]
      interval: 30s
      timeout: 5s
      retries: 3
  cambpm:
    image: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee:${CAMBPM_VERSION:-7.19.0}
    container_name: cambpm
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - DB_URL=jdbc:postgresql://postgres:5432/engine
      - TZ=Europe/Berlin
      - JAVA_OPTS=-Xms2g -Xmx2g -XX:MaxMetaspaceSize=256m
    ports:
      - 8080:8080
    volumes:
      - "./optimize/backend/target/cambpm_logs:/camunda/logs"
      - "./optimize/backend/src/it/resources/tomcat/bpm-platform.postgresql.xml:/camunda/conf/bpm-platform.xml"
      - "./optimize/backend/src/it/resources/tomcat/tomcat-users.xml:/camunda/conf/tomcat-users.xml"
      - "./optimize/backend/src/it/resources/tomcat/context.xml:/camunda/webapps/manager/META-INF/context.xml"
    restart: always
    mem_limit: 3g
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:8080/engine-rest/engine | grep -q default"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
    - postgres
  postgres:
    image: postgres:16.3@sha256:1bf73ccae25238fa555100080042f0b2f9be08eb757e200fe6afc1fc413a1b3c
    container_name: postgres
    command: ["postgres", "-c", "max_connections=200", "-c", "effective_cache_size=4GB", "-c", "shared_buffers=2GB", "-c", "synchronous_commit=off", "-c", "log_statement=none", "-c", "checkpoint_timeout=600", "-c", "max_wal_size=30GB"]
    environment:
    - POSTGRES_USER=camunda
    - POSTGRES_PASSWORD=camunda
    - POSTGRES_DB=engine
    - TZ=Europe/Berlin
    ports:
    - 5432:5432
    restart: always
    mem_limit: 4g
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$${POSTGRES_PASSWORD} psql --username=$${POSTGRES_USER} --host=localhost --dbname=$${POSTGRES_DB} --command='\\q'"]
      interval: 30s
      timeout: 5s
      retries: 3


