version: "3.9"
services:
  cambpm-postgres:
    container_name: cambpm-postgres
    image: postgres:${POSTGRES_VERSION:-11.2}
    command:
    - -c
    - max_connections=200
    - -c
    - effective_cache_size=4GB
    - -c
    - shared_buffers=2GB
    - -c
    - synchronous_commit=off
    - -c
    - log_statement=none
    - -c
    - checkpoint_timeout=600
    - -c
    - max_wal_size=30GB
    environment:
      POSTGRES_DB: ${PGDATABASE:-engine}
      POSTGRES_PASSWORD: ${PGPASSWORD:-camunda}
      POSTGRES_USER: ${PGUSER:-camunda}
      TZ: ${TZ:-Europe/Berlin}
    deploy:
      resources:
        limits:
          cpus: "12"
          memory: 68g
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready
      interval: 10s
      retries: 5
      timeout: 5s
    labels:
    - service=cambpm-postgres
    ports:
    - 5432:5432
    volumes:
    - ${RUNNER_TEMP:-.}/cambpm/pgdata:/var/lib/postgresql/data

  cambpm-ee:
    depends_on:
      cambpm-postgres:
        condition: service_healthy
    container_name: campbpm
    image: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee:${CAMBPM_VERSION:-7.19.0}
    environment:
      DB_CONN_MAXACTIVE: 500
      DB_CONN_MAXIDLE: 500
      DB_CONN_MINIDLE: 150
      DB_DRIVER: org.postgresql.Driver
      DB_PASSWORD: ${PGPASSWORD:-camunda}
      DB_URL: jdbc:postgresql://cambpm-postgres:5432/${PGDATABASE:-engine}
      DB_USERNAME: ${PGUSER:-camunda}
      JAVA_OPTS: >-
        -Xms2g -Xmx2g
        -XX:+CMSParallelRemarkEnabled
        -XX:+CMSScavengeBeforeRemark
        -XX:+ScavengeBeforeFullGC
        -XX:+UseCMSInitiatingOccupancyOnly
        -XX:+UseConcMarkSweepGC
        -XX:CMSInitiatingOccupancyFraction=70
        -XX:MaxMetaspaceSize=256m
      TZ: ${TZ:-Europe/Berlin}
      WAIT_FOR: cambpm-postgres:5432
      WAIT_FOR_TIMEOUT: 300
    deploy:
      resources:
        limits:
          cpus: "16"
          memory: 12g
    healthcheck:
      test:
      - CMD-SHELL
      - curl --fail http://localhost:8080/engine-rest/engine
      interval: 10s
      retries: 20
      timeout: 5s
    labels:
    - service=cambpm
    ports:
    - 8080:8080
    volumes:
    - ${RUNNER_TEMP:-.}/cambpm/logs:/camunda/logs
