version: "2.4"
services:
  cambpm:
    extends:
      file: ./docker-compose.cambpm.yml
      service: cambpm
    network_mode: host
    environment:
      - DB_DRIVER=${DB_DRIVER:-org.postgresql.Driver}
      - DB_USERNAME=${DB_USERNAME:-camunda}
      - DB_PASSWORD=${DB_PASSWORD:-camunda}
      - DB_URL=${DB_URL:-jdbc:postgresql://localhost:5432/engine}
