version: "3.9"
services:
  nginx:
    extends:
      service: nginx
      file: ./docker-compose.nginx.yml
    volumes:
      - ./optimize.crt:/etc/nginx/certs/optimize.crt
      - ./optimize.key:/etc/nginx/certs/optimize.key
      - ./ssl-auth.cfg:/opt/auth.conf
