version: "3.9"
services:
  nginx:
    extends:
      service: nginx
      file: ./docker-compose.nginx.yml
    environment:
      HTPASSWD: ${NGINX_HTPASSWD:-elastic:$$apr1$$rAPWdsDW$$/7taaK2oH4AwXgLTbYSpa0}
