version: "3.9"
services:
  elasticsearch:
    extends:
      service: elasticsearch
      file: ./docker-compose.elasticsearch.yml
    network_mode: host
    cap_add:
      - IPC_LOCK
      - SYS_RESOURCE
