version: "2.4"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-15.4}
    container_name: postgres
    command:
      [
        "postgres",
        "-c",
        "max_connections=200",
        "-c",
        "effective_cache_size=4GB",
        "-c",
        "shared_buffers=2GB",
        "-c",
        "synchronous_commit=off",
        "-c",
        "log_statement=none",
        "-c",
        "checkpoint_timeout=600",
        "-c",
        "max_wal_size=30GB",
      ]
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-camunda}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-camunda}
      - POSTGRES_DB=${POSTGRESS_DB:-engine}
      - TZ=Europe/Berlin
    ports:
      - 5432:5432
    restart: always
    volumes:
      - /var/tmp:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "PGPASSWORD=${POSTGRES_PASSWORD} psql --username=${POSTGRES_USER:-camunda} --host=localhost --dbname=${POSTGRESS_DB:-engine} --command='\\q'",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
