name: Optimize health status report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1-5"

permissions:
  contents: read
  actions: read
  pull-requests: read

jobs:
  health-status-report:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Import secrets
        id: secrets
        uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/optimize/ci/camunda-optimize SLACK_API_KEY;
            secret/data/products/optimize/ci/camunda-optimize ARGOCD_TOKEN;

      - name: Genetare config file
        run: |
          cd ${{ github.workspace }}/.github/scripts/healthStatusReport
          yarn
          npx ts-node createHealthStatusConfig.ts
          cat config.json

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get health status report
        uses: misiekhardcore/infra-report-action@42096709b605df6eb1a5d4630dffb5350d915187 # v1.5.0
        id: get-report
        with:
          config_file_path: ${{ github.workspace }}/.github/scripts/healthStatusReport/config.json
          github_token: ${{ secrets.GITHUB_TOKEN }}
          argocd_token: ${{ steps.secrets.outputs.ARGOCD_TOKEN }}

      - name: Send report to slack channel
        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
        with:
          channel-id: "#optimize-status"
          slack-message: ${{ steps.get-report.outputs.infra_report }}
        env:
          SLACK_BOT_TOKEN: ${{ steps.secrets.outputs.SLACK_API_KEY }}
