name: Optimize e2e tests sm

on:
  pull_request:
  push:
    branches:
      - master
      - maintenance/*
      - release/*
  workflow_dispatch:

# Will limit the workflow to 1 concurrent run per ref (branch / PR)
# If a new commits occurs, the current run will be canceled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for git clone
  id-token: write # for authenticating with GCP

jobs:
  e2e-tests-sm:
    name: E2E tests sm
    runs-on: gcp-core-4-default
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Login to Harbor registry
        uses: ./.github/actions/login-registry
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: "Parse pom.xml for versions"
        id: "pom_info"
        uses: YunaBraska/java-info-action@main

      - name: Setup Maven
        uses: ./.github/actions/setup-maven
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Install firefox deps 
        run: |
          sudo apt-get update && sudo apt-get install
          sudo apt-get install -y xvfb bzip2 packagekit-gtk3-module libasound2

      - name: Install firefox
        uses: browser-actions/setup-firefox@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.pom_info.outputs.x_version_node }}

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup yarn cache
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: ${{ steps.pom_info.outputs.x_version_node }}
          cache: "yarn"
          cache-dependency-path: optimize/client/yarn.lock

      - name: Build backend & frontend
        run: mvn clean install -DskipTests -Dskip.docker -pl optimize/backend,optimize/qa/data-generation -am

      - name: Start zeebe, operate, keycloak, identity and Elasticsearch
        uses: ./.github/actions/compose
        with:
          compose_file: ${{ github.workspace }}/optimize/client/docker-compose.yml
          project_name: e2e
          additional_flags: "--profile self-managed"

      - name: Create backend logs file
        run: mkdir -p ./optimize/client/build && touch ./optimize/client/build/backendLogs.log

      - name: Start back-end
        working-directory: ./optimize/client
        run: |
          yarn run start-backend ci &> ./build/backendLogs.log &

      - name: Start front-end
        working-directory: ./optimize/client
        run: yarn start &

      - name: Wait for import to complete
        run: |
          while : ; do
            count=$(curl -s -X GET "http://localhost:9200/optimize-process-definition/_count" | jq '.count')
            if [[ $count -eq 49 ]]; then
              echo "Import Completed"
              break
            fi
            echo "Index has $count entities. Waiting for 49..."
            sleep 10
          done

      - name: Wait for front-end to start
        run: ./.github/scripts/wait-for.sh http://localhost:3000/ready

      - name: Run tests
        working-directory: ./optimize/client
        run: yarn run e2e:ci:sm:headless

      - name: Upload logs
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        if: always()
        with:
          name: logs
          path: ./optimize/client/build/*.log

      - name: Docker log dump
        uses: ./.github/actions/docker-logs
        if: always()
        with:
          archive_name: e2e-docker-logs
