name: Optimize Cluster Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1-5"

jobs:
  optimize-cluster-test:
    runs-on: gcp-core-8-default
    timeout-minutes: 60
    env:
      NAMESPACE: optimize-cluster-test-${{ github.run_id }}

    steps:
    - name: Checkout code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

    - name: Import secrets
      id: secrets
      uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        secrets: |
          secret/data/products/optimize/ci/camunda-optimize CI_SERVICE_ACCOUNT | GCP_CREDENTIALS;
          secret/data/products/optimize/ci/camunda-optimize SLACK_BOT_URL;

    - name: Setup Maven
      uses: ./.github/actions/setup-maven
      with:
          secrets: ${{ toJSON(secrets) }}
          java-version: 21
          distribution: zulu

    - name: Install extra Dependencies
      run: |
        sudo apt update -qq
        sudo apt install -y netcat

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa # v2
      with:
        credentials_json: ${{ steps.secrets.outputs.GCP_CREDENTIALS }}

    - name: Get gcloud credentials
      uses: 'google-github-actions/get-gke-credentials@c544a3d7e92276d24e03a5632a53aa3913ad5d8a' # v2
      with:
        cluster_name: 'camunda-ci'
        location: 'europe-west1'

    - name: Configure Google SDK
      uses: google-github-actions/setup-gcloud@98ddc00a17442e89a24bbf282954a3b65ce6d200 # v2.1.0
      with:
        install_components: gke-gcloud-auth-plugin, kubectl

    - name: Read pom.xml file
      id: pom-info
      uses: YunaBraska/java-info-action@main

    - name: Deploy cluster
      run: .github/podSpecs/clusterTests/deploy.sh $NAMESPACE ${{ steps.pom-info.outputs.x_elasticsearch8_test_version }} ${{ steps.pom-info.outputs.x_camunda_engine_version }}

    - name: Run Tests
      uses: ./.github/actions/run-maven
      with:
          parameters: >-
                  -B -Pclustering-tests verify -pl optimize/qa/clustering-tests
                  -Doptimize.importing.host=optimize-import.$NAMESPACE -Doptimize.importing.port=8090
                  -Doptimize.notImporting.host=optimize-no-import.$NAMESPACE -Doptimize.notImporting.port=8090
                  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - name: Store elasticsearch logs
      if: always()
      run: kubectl -n $NAMESPACE logs elasticsearch-0 -c elasticsearch > elasticsearch.log

    - name: Cluster cleanup
      if: always()
      run: .github/podSpecs/clusterTests/kill.sh $NAMESPACE

    - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
      if: always()
      with:
        name: elasticsearch-logs
        path: ./elasticsearch.log

    - name: Post results on slack
      if: failure() && github.event_name != 'schedule'
      uses: ./.github/actions/notify-on-slack
      with:
        slack_webhook_url: ${{ steps.secrets.outputs.SLACK_BOT_URL}}
        status: ${{ job.status }}
