name: Optimize Check renovate configuration

on:
  pull_request:
    paths:
      - ".github/renovate.json5"

jobs:
  check-renovate-config:
    name: Configuration check
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: "Parse pom.xml for versions"
        id: "pom_info"
        uses: YunaBraska/java-info-action@main

      - name: Setup npm
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: ${{ steps.pom_info.outputs.x_version_node }}

      - name: Validate config file
        run: |
          npm i -g renovate
          renovate-config-validator ${{ github.workspace }}/.github/renovate.json5
