name: Optimize test dockerfiles with Hadolint
on: [pull_request]
jobs:
  hadolint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          [
            "optimize.Dockerfile",
            "optimize/qa/clustering-tests/src/main/docker/optimize/Dockerfile",
          ]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
          ignore: DL3018,DL3008
