name: Optimize Javascript code scan

on:
  pull_request:
    branches:
      - "master"
      - "maintenance/**"
      - "release/**"
    paths:
      - "**/*.js"
      - "**/*.tsx"
      - "**/*.ts"
  schedule:
    - cron: "30 2 * * 1-5"
  workflow_dispatch: # can be used to trigger the workflow manually

jobs:
  codeql-analysis-javascript:
    name: code-scanning-javascript
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # v3
        with:
          languages: javascript-typescript
          queries: security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # v3
