name: Optimize Java code scan

on:
  pull_request:
    branches:
      - "master"
      - "maintenance/**"
      - "release/**"
    paths:
      - "optimize/backend/src/**/*.java"
      - "optimize/util/**/*.java"
  schedule:
    - cron: "30 2 * * 1-5"
  workflow_dispatch: # can be used to trigger the workflow manually

jobs:
  codeql-analysis-java:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Import secrets
        id: secrets
        uses: hashicorp/vault-action@148ee648ccb26f28892776406f3c3c4cf8ac033f
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}

      - name: Setup Maven
        uses: ./.github/actions/setup-maven
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # v3
        with:
          languages: java
          queries: security-and-quality

      - name: Compile
        uses: ./.github/actions/run-maven
        with:
          parameters: compile -DskipTests -Dskip.docker

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # v3