name: Optimize Import Mediator Permutation Test

on:
  schedule:
    - cron: "0 0 * * 1-5"

permissions:
  contents: read
  actions: read

jobs:
  migrate-import-mediator-permutation:
    runs-on: gcp-core-16-default
    timeout-minutes: 80
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Setup Maven
        uses: ./.github/actions/setup-maven
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Login to Harbor registry
        uses: ./.github/actions/login-registry
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: "Read Java / Version Info"
        id: "pom-info"
        uses: YunaBraska/java-info-action@main
      - name: Start Cambpm
        uses: ./.github/actions/compose
        with:
          compose_file: ${{ github.workspace }}/.github/actions/compose/docker-compose.cambpm.yml
          project_name: cambpm
        env:
          CAMBPM_VERSION: ${{ steps.pom-info.outputs.x_camunda_engine_version }}
          CAMBPM_JVM_MEMORY: 8
      - name: Start Elastic
        uses: ./.github/actions/compose
        with:
          compose_file: ${{ github.workspace }}/.github/actions/compose/docker-compose.elasticsearch.yml
          project_name: elasticsearch
        env:
          ELASTIC_VERSION: ${{ steps.pom-info.outputs.x_elasticsearch8_test_version }}
          ELASTIC_JVM_MEMORY: 16
          ELASTIC_HTTP_PORT: 9200
      - name: Run Maven
        shell: bash
        run: |
          mvn install -Dskip.docker -Dskip.fe.build -DskipTests -pl optimize/backend,optimize/qa -am -Pengine-latest -B --fail-at-end -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          mvn -f optimize/qa/import-mediator-permutation-test/pom.xml clean verify -Pimport-mediator-permutation-test -B --fail-at-end -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
